name: Deploy Manually

on:
  workflow_dispatch:
    inputs:
      redeploy:
        type: boolean
        default: false
      channel:
        type: string
        default: release
      findBy:
        type: string
        default: ""
      version:
        type: string
        default: "1.2.0"
      changelog:
        type: string
        default: ""
      versionsdbremote:
        type: string
        default: master
      mcpelauncher-manifest:
        type: string
        default: ""
      mcpelauncher-manifest-qt6:
        type: string
        default: ""
      mcpelauncher-ui-manifest:
        type: string
        default: ""
      mcpelauncher-ui-manifest-qt6:
        type: string
        default: ""

jobs:
  build:
    if: "!inputs.redeploy"
    uses: ./.github/workflows/build-linux.yml
    with:
      channel: ${{ inputs.channel }}
      version: ${{ inputs.version }}
      changelog: ${{ inputs.changelog }}
      versionsdbremote: ${{ inputs.versionsdbremote }}
      shas: |-
        {
          "mcpelauncher-manifest": {
            "": ${{ tojson(inputs.mcpelauncher-manifest || '') }},
            "qt6": ${{ tojson(inputs.mcpelauncher-manifest-qt6 || '') }}
          },
          "mcpelauncher-ui-manifest": {
            "": ${{ tojson(inputs.mcpelauncher-ui-manifest || '') }},
            "qt6": ${{ tojson(inputs.mcpelauncher-ui-manifest-qt6 || '') }}
          }
        }

  deploy:
    if: "!failure() && !cancelled()"
    permissions:
      contents: read
      pages: write
      id-token: write
      actions: read
    needs: build
    uses: ./.github/workflows/update-repo.yml
    secrets: inherit
    with:
      channel: ${{ inputs.channel }}
      findBy: ${{ inputs.findBy }}

  update-version:
    if: "!failure() && !cancelled() && !inputs.redeploy && inputs.channel == 'release'"
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - uses: actions/checkout@v4
    - run: echo "${{ inputs.version }}" > version.txt
    - name: Commit changes
      run: |
        # from https://github.com/orgs/community/discussions/26560
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add .
        git commit -m "Released ${{ inputs.version }}"
        git push