on:
  workflow_dispatch:
jobs:
  verify:
    strategy:
      matrix:
        distro:
        - bullseye
        - bookworm
        arch:
        - amd64
        - arm64
    runs-on: ubuntu-latest
    steps:
    - run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker run --rm --platform linux/${{ matrix.arch }} debian:${{ matrix.distro }} bash -c 'apt update && apt install -y sudo curl && curl -sS https://minecraft-linux.github.io/pkg/deb/pubkey.gpg | sudo tee -a /etc/apt/trusted.gpg.d/minecraft-linux-pkg.asc && echo "deb [arch=amd64,arm64] https://minecraft-linux.github.io/pkg/deb bookworm-nightly main" | sudo tee /etc/apt/sources.list.d/minecraft-linux-pkg.list && apt update && apt install -y mcpelauncher-manifest mcpelauncher-ui-manifest msa-manifest && ldd $(which mcpelauncher-ui-qt) && ldd $(which mcpelauncher-client) && ldd $(which mcpelauncher-webview)'
